### ISSUE TITLE
IOCTL error on BLKRRPART: Device or resource busy

### ISSUE THREAD

**Issue by prusrai3** [grml/grml#123]
![grml error](https://user-images.githubusercontent.com/17263783/50734577-20ebd000-11c7-11e9-9ee3-6901723a389b.jpeg)

I am unable to continue after this screenshot. Please advice

**Comment by jkirk** [comment]
It seems like you run [grml-debootstrap](https://github.com/grml/grml-debootstrap/).

Please provide some information on what you did and tried to do. The screenshot indicates that you tried to install Debian on `/dev/sda10` and `grml-debootstrap` refused to do so because it detected an ext4 file system. This behavior is by design to prevent data loss and does not seem like a bug. If you have questions regarding the usage of `grml-debootrap` the [man page](http://grml.org/grml-debootstrap/) and/or the  [Grml user mailing list](http://grml.org/contact/#mailinglist) are good starting points.

**Comment by prusrai3** [comment]
KDE Neon: grml install

I wish to install the latest image, through grml or imageboot. The problem is it says casper/vmlinuz.efi not found, load the kernel first.

It would be great help if someone could give the correct boot entry that I can edit in grub to make this work.

present grub.cfg of image

menuentry "Start KDE neon" {
    load_video
    set gfxpayload=keep
    linux   /casper/vmlinuz  boot=casper apparmor=0 quiet splash ---
    initrd  /casper/initrd.lz
}

menuentry "Start KDE neon (OEM mode)" {
    load_video
    set gfxpayload=keep
    linux   /casper/vmlinuz  boot=casper apparmor=0 quiet splash --- oem-config/enable=true
    initrd  /casper/initrd.lz
}

**Comment by mika** [comment]
Uhm, this grub.cfg is not related to Grml at all but looks like for a Ubuntu(-based) system. I've truly no idea what you're trying to do. Are you maybe looking for [grml-rescueboot](https://packages.debian.org/buster/grml-rescueboot)?
