### ISSUE TITLE
Booting KDE Neon fails with "vmlinuz.efi not found"

### ISSUE THREAD

**Issue by benguyer** [grml/grml#126]
Hi, I'm not particularly knowledgeable about Grub or Linux, so apologies if this is a known issue or if I'm not providing all the relevant info. I installed grml-rescueboot from the Ubuntu 18.04 repositories. I tried to manually download the most recent version to verify this was still and issue by following the instructions [here](https://wiki.grml.org/doku.php?id=rescueboot), but the "setup" section downloads lagged the point I couldn't get anywhere with them.

Anyway, I was hoping to use grml-rescueboot as detailed on the [Ubuntu Grub2/ISOBoot help page](https://help.ubuntu.com/community/Grub2/ISOBoot). I Downloaded a copy of KDE Neon from KDE's page [here](neon-useredition-20190124-0530-amd64.iso). I moved the file to `/boot/grml` and ran `update-grub`. This appeared to work as expected, and the menu entry appeared in Grub on boot.

However, when I selected that Grub entry, I got the following error:

    error: file `/casper/vmlinuz.efi' not found.
    error: you need to load the kernel first.

In the KDE Neon ISO, the kernel executable is called 'vmlinuz' instead of 'vmlinuz.efi', which explains the error.

To boot from the ISO, I ended up manually editing the menu entry in `/etc/grub.d/40_custom`, following the second example [here](https://help.ubuntu.com/community/Grub2/ISOBoot#Menuentry_Example). Specifically the line: 

    linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$isofile noprompt noeject

This caused booting from the ISO to work as expected. Since it works for me now, I don't exactly need to find a solution -- I just wanted to make sure that this issue was known. Let me know if there's anything I can do to help.

**Comment by mika** [comment]
(Sorry for the late reply, somehow this issue was overlooked by us so far. :-/)

Thank you for reporting this towards us, though this looks like an issue with the KDE Neon ISO to me. grml-rescueboot basically supports only Grml ISOs, and while Ubuntu ISOs are usually known to work fine as well, it looks like KDE Neon does something else that prevents grml-rescueboot to work as needed out of the box.

If someone is willing to work on this that's surely welcome, but it's out of scope for me personally due to lack of time, so I'm closing this hereby for now.
