### ISSUE TITLE
uefi mode clonezilla.

### ISSUE THREAD

**Issue by opqriu** [grml/grml#168]
I use Debian 10.  I downloaded the latest 64bit clonezilla and stable 64&32bit clonezilla.  I put three iso files, (sudo update-grub), and the utility added grub menu as normal.  But when I select it in grub nothing happens.  It seems that clonezilla is not working in uefi mode.
thank you.

**Comment by mika** [comment]
@opqriu I'm a bit confused by your bug report, to be honest. :) This is the issue tracker of [Grml.org](https://grml.org/) (the Grml live system), while your issue seems to be related to Clonezilla? Why/how did you end up here? Are you using `grml-rescueboot`? If so, the ISOs supported by `grml-rescueboot` are only Grml ones, if that wasn't clear enough I'd be interested to understand, why you thought you could grml-rescueboot with Clonezilla, where did you get that information from?

**Comment by opqriu** [comment]
Oh, I'm sorry.  I really didn't know it and it wasn't intentional.  I misunderstood that it is an app that boots all iso stored on the hard disk.
