### ISSUE TITLE
90 second delay when connecting via ssh if an NFS share is unavailable

### ISSUE THREAD

**Issue by graysky2** [grml/grml#174]
**Describe the bug**
90 second delay when connecting via ssh if an NFS share is unavailable

**Steps To Reproduce**
1. Define a NFS share in `/etc/fstab` such as `10.1.2.101:/scratch /scratch  nfs  noauto,fg,nofail,x-systemd.automount,_netdev 0 0`
2. Make sure the server defined is not exporting NFS
3. Connect to the box via ssh

**Expected behavior**
No delay should be experienced.

**In which Grml Version did the bug occur?**

Output of `grml-version`:
Arch Linux does not provide this executable but the package I am using is grml-zsh-config 0.19.0-1

**Additional context**
The problem seems to occur in `/etc/zsh/zshrc` and can be seen as systemd timeout waiting for the share:
```
% ssh targetbox
<< 90 sec delay >>
/etc/zsh/zshrc:cd:1723: no such device: /scratch
```

If I comment out lines 1718-1724, connection is instantaneous.

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…

**Comment by mika** [comment]
@graysky2 this seems to be triggered by having `/scratch` in your `$HOME/.zdirs`? If you remove the directory from there, the issue should be gone. You should be able to _permanently_ disable this dirstack feature by adding the following snippet to your `${HOME}}/.zshrc.pre`:

  `zstyle ':grml:chpwd:dirstack' enable false`

Or if you prefer to keep the feature enabled, but ignore `/scratch`, this should also do the trick:

```
# don't push certain directories to dirstack
function my_dirstack_filter() { [[ $1 == /scratch(|/*) ]] }
zstyle ':grml:chpwd:dirstack' filter my_dirstack_filter 
```

BTW, how did you end up in this repository? Just curious, because the proper place for grml-zshrc would have been https://github.com/grml/grml-etc-core/, and if we could clarify this somewhere, I'd like to know :)

@ft do you have any idea, how we could further improve this within our dirstack feature? :)

**Comment by graysky2** [comment]
@mika - Thanks, I added the `zstyle ..` line to my `~/.zshrc` and found no delay.  I found this by a simple search... maybe 'github grml zsh config' or the like.  I didn't spend much time looking at other repos ... probably should have, sorry about the extra noise.

**Comment by mika** [comment]
I see, thanks for your feedback. :) I'll close the issue hereby, if @ft or anyone else has any further ideas for improvements, I'd appreciated that!
