### ISSUE TITLE
Update Memtest86+

### ISSUE THREAD

**Issue by romanrm** [grml/grml#178]
The latest 2021.07 release still includes the old Memtest86+ 5.01.
(I mean the one available in "Addons" on the boot selection screen.)

This version no longer works properly on modern systems, such as some AMD Ryzen boards.
On https://www.memtest.org/ there's version 5.31b, which works.
Although at this moment it says that version is not ready for production. So maybe include both for now?

Thanks

**Comment by mika** [comment]
Thanks for bringing this to our attention. We use the memtest86+ file as shipped by Debian's memtest86+ package, so the proper way to get this sorted out is to ensure that the memtest86+ package get's updated within Debian. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977217 + https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989030, I sent a friendly ping there.

**Comment by jkirk** [comment]
Grml 2022.11 ships MemTest86+ v6.00 but only when booting with Grub (EFI + BIOS).

When booting ISOLINUX (BIOS) we still end up in MemTest86+ v5.01!

This is because the isolinux configuration ([isolinux/addon_40_memtest.cfg](https://github.com/grml/grml-live/blob/master/templates/boot/isolinux/addon_40_memtest.cfg)) is not able to automatically detect the available memtest versions (unlike Grub: [grub/addons.cfg](https://github.com/grml/grml-live/blob/master/templates/boot/grub/addons.cfg)).

For reference: grml/grml-live#109 + https://github.com/grml/grml-live/commit/c01a86b3fc9055a06f38db11b9e908b5fe03701f
