### ISSUE TITLE
"Starting ATA over Ethernet discovery..." in default boot

### ISSUE THREAD

**Issue by mika** [grml/grml#32]
This looks like it shouldn't automatically run, needs investigation.

**Comment by mika** [comment]
So there's `/lib/systemd/system/aoe-discover.service` which looks like that (also see http://sources.debian.net/src/aoetools/36-2/debian/aoetools.aoe-discover.service/):

```
[Unit]
Description=ATA over Ethernet discovery
BindsTo=sys-devices-virtual-aoe-discover.device
DefaultDependencies=no
Conflicts=shutdown.target
After=network-online.target

[Service]
Type=oneshot
ExecStart=/sbin/aoe-discover
```

**Comment by jkirk** [comment]
Please be aware that "Version 36-2 of aeotools is marked for autoremoval from testing on 2017-05-29" (see: https://packages.qa.debian.org/a/aoetools.html) because of Debian-Bug [#862530](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=862530).

That said, maybe masking the service or restricting the aoe kernel module (see: `/lib/modules-load.d/aeotools.conf`) could be an option.

**Comment by mika** [comment]
Thanks @jkirk, that's related to the suggestion by @fsateler - since the `aeotools.conf` file tells systemd to load the aoe module which in turn triggers the udev rule, so masking that single file should be enough and then aoe is a simple a modprobe away. :)

Thanks, folks!
