### ISSUE TITLE
integrate EFI-capable netboot.xyz

### ISSUE THREAD

**Issue by mika** [grml/grml#49]
I was forwarded the information (thanks, @jimmy42 :)) that netboot upstream has a EFI binary available which needs testing: https://boot.netboot.xyz/ipxe/netboot.xyz.efi (and if it works fine we should consider integrating it into our ISOs :)) /cc @schierlm

**Comment by antonym** [comment]
Working a bit on the EFI support from inside netboot.xyz and memdisk won't work within the EFI implementation which keeps me from loading the grml ISO.  If the contents of the ISO or netboot packages were extracted and hosted, I could boot from those instead of using the ISO which would probably speed up loading on the image quite a bit.

Anyways something to think about.

**Comment by mika** [comment]
I just integrated the EFI capable netboot.xyz into our boot addons in https://github.com/grml/grml-live-grml/commit/7e0f778543cb6127ce88f27bbb63fc62b8cdd6b5 and the build procedure supports it via https://github.com/grml/grml-live/commit/257dba7150b349ae0cede679f8fcc078a0d13f2f

This should be everything what's needed, thanks to @antonym for netboot.xyz!
