### ISSUE TITLE
Cannot unmount filesystem after usage of grml-chroot

### ISSUE THREAD

**Issue by Mebus** [grml/grml#74]
Hallo,

if I mount a file system for instance under /mnt/chroot/ and I use grml-chroot on it, it is not possible to unmount the filesystem afterwards, because of this:

> devpts on /mnt/chroot/dev/pts type devpts (rw,relatime,mode=622,ptmxmode=000)

This cannot be unmounted:

> root@grml ~ # umount /mnt/chroot/dev/pts
umount: /mnt/chroot/dev/pts: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
32 root@grml ~ #   

This seems to be a bug. Is there some kind of workaround for this?

Mebus

**Comment by Mebus** [comment]
I think grml should mount devpts with the "newinstance" option to fix this, see: http://elixir.free-electrons.com/linux/v3.14/source/Documentation/filesystems/devpts.txt

Mebus

**Comment by mika** [comment]
This is the same issue as https://github.com/grml/grml-scripts/issues/4

Thanks for the pointer towards `newinstance`, I wasn't aware of this yet. (Any PRs welcome, just saying :))

**Comment by mika** [comment]
JFTR, I looked into the newinstance situation, might be tricky WRT /dev/pts/ptmx and it seems to be relevant mainly for container usage (see e.g. https://bugzilla.redhat.com/show_bug.cgi?id=501718) and the underlying issue seems to be resolved with https://github.com/grml/grml-scripts/issues/4 with taking care of the right order with mounting/umounting the filesystems.

If there's anything further we should do please let us know, thanks!
