### ISSUE TITLE
Consider default consoleblank=0

### ISSUE THREAD

**Issue by ivan** [grml/grml#84]
While waiting a long time for grml to boot (due to slow virtual devices, etc), the console blanks after 10 minutes and hides progress information until a key is pressed.  I think this can be avoided by booting with `consoleblank=0` (also the default in Linux 4.12+).  I believe the default changed because burn-in is no longer a problem with the vast majority of displays.

**Comment by mika** [comment]
Excellent point, thanks for raising that!

**Comment by mika** [comment]
What's the opinion of others (@jkirk @formorer @evgeni) regarding usage of `consoleblank=0` by default? Any other ideas?

**Comment by mika** [comment]
ACK, good point, just double-checked, this is available since https://github.com/torvalds/linux/commit/a4199f5eb8096d63828f7333fa45650a7b0a99ed, and since we're already using kernel 4.17 in our current daily ISOs we don't have take care for our upcoming stable release.

Closing, thanks for raising this @ivan and @evgeni for the fast feedback. :)
