### ISSUE TITLE
check cheatcodes for deprecated boot options

### ISSUE THREAD

**Issue by mika** [grml/grml#9]
Now with the switch to systemd we need to make sure that the docs (http://grml.org/cheatcodes/ -> https://git.grml.org/?p=grml-live.git;a=blob_plain;f=templates/GRML/grml-cheatcodes.txt;hb=HEAD) match what's actually provided.

**Comment by jkirk** [comment]
Let's start with the isolinux bootprompt options:
- [ ] grml                               - Use default settings (same as just pressing return)
- [ ] grml2ram                           - Copy Grml's squashfs file to RAM and run from there (compare with 'grml toram')
- [ ] memtest                            - Run Memtest86+ instead of Linux
- [ ] fb1280x1024                        - Use fixed framebuffer graphics (1)
- [ ] fb1024x768                         - Use fixed framebuffer graphics (2) [notice: Grml's default]
- [ ] fb800x600                          - Use fixed framebuffer graphics (3)
- [ ] nofb                               - Disable framebuffer
- [ ] floppy                             - Boot from floppydisk
- [ ] hd / hd1 / hd2 / hd3               - Boot from (local) primary / secondary /... harddisk
- [ ] debug                              - Get shells during process of booting for debugging
- [ ] bootchart                          - Create chart of booting sequence in /var/log/bootchart.tgz
- [ ] forensic                           - Do not touch any harddisks during hardware recognition
- [ ] serial                             - Activate ttyS0 and start a getty
- [ ] grub                               - Boot Grub bootloader (special all-in-one-image)
- [ ] dos                                - Boot FreeDOS
- [ ] hdt                                - Boot Hardware Detection Tool (from syslinux project)

**Comment by jkirk** [comment]
Isolinux bootoption `grub` fails with:
```
boot: grub
Loading grub... failed: No such file or directory
```

**Comment by jkirk** [comment]
Ah, `grub2` works. Should we create an alias or shall we change the menu?

**Comment by jkirk** [comment]
Boot option `forensic` reports the following:
```
[ WARN ] Skipping SW-RAID code as requested on boot commandline.
[ WARN ] Skipping dmraid code as requested on boot commandline.
[ WARN ] Skipping LVM code as requested on boot commandline.
[ WARN ] Skipping running automount of device(s) labeled GRMLCFG as requested.
```
Seems ok.

**Comment by jkirk** [comment]
Boot option `bootchart` does not seem to work.

A look at the [isolinux configuration](https://github.com/grml/grml-live/blob/master/templates/boot/isolinux/hidden.cfg#L19) shows that it expects `/sbin/bootchartd` but the package `bootchart2` is not part of any current Grml configuration. @mika: Should we add it?

**Comment by jkirk** [comment]
While we should also make the "Additional boot entries" consistent between [isolinux](https://github.com/grml/grml-live/blob/master/templates/boot/isolinux/grml.cfg) and [grub](https://github.com/grml/grml-live/blob/master/templates/boot/grub/%25SHORT_NAME%25_options.cfg).

**Comment by jkirk** [comment]
Related to #10

**Comment by jkirk** [comment]
This issues was stale for a very long time.

As of Grml-daily grml64-full_sid build4636, the isolinux bootprompt options should be re-tested:

- ✅ grml                               - Use default settings (same as just pressing return)
- ✅ grml2ram                           - Copy Grml's squashfs file to RAM and run from there (compare with 'grml toram')
- ✅ memtest                            - Run Memtest86+ instead of Linux
- ❌  fb1280x1024                        - Use fixed framebuffer graphics (1)
- ❌ fb1024x768                         - Use fixed framebuffer graphics (2) [notice: Grml's default]
- ❌ fb800x600                          - Use fixed framebuffer graphics (3)
- ✅ nofb                               - Disable framebuffer
- 🌥️   floppy                             - Boot from floppydisk
- ❌  hd / hd1 / hd2 / hd3               - Boot from (local) primary / secondary /... harddisk
- ❌ debug                              - Get shells during process of booting for debugging
- ✅ forensic                           - Do not touch any harddisks during hardware recognition
- ❓  serial                             - Activate ttyS0 and start a getty
- ✅ grub                               - Boot Grub bootloader (special all-in-one-image)
- 🌥️  dos                                - Boot FreeDOS
- ✅ hdt                                - Boot Hardware Detection Tool (from syslinux project)

Notes:

The fixed framebuffer graphics do not work as expected (at least in an VirtualBox VM with VMSVGA Graphics Controller):

`nofb` works:
```
Oct 03 14:01:33 grml kernel: Booted with the nomodeset parameter. Only the system framebuffer will be available
Oct 03 14:01:33 grml kernel: signal: max sigframe size: 1776
```

`fb800x600` changes from 100x37 to 160x50:
```
Oct 03 13:54:50 grml kernel: signal: max sigframe size: 1776
Oct 03 13:54:50 grml kernel: vesafb: framebuffer at 0xe0000000, mapped to 0x00000000e4e80e79, using 1875k, total 34816k
Oct 03 13:54:50 grml kernel: Console: switching to colour frame buffer device 100x37
Oct 03 13:54:50 grml kernel: fb0: VESA VGA frame buffer device
Oct 03 13:54:52 grml kernel: Console: switching to colour frame buffer device 160x50
Oct 03 13:54:52 grml kernel: vmwgfx 0000:00:02.0: [drm] fb0: vmwgfxdrmfb frame buffer device
```

`fb1024x768` changes from 128x48 to 160x50:
```
Oct 03 14:08:08 grml kernel: signal: max sigframe size: 1776
Oct 03 14:08:08 grml kernel: vesafb: framebuffer at 0xe0000000, mapped to 0x0000000049dc8091, using 3072k, total 34816k
Oct 03 14:08:08 grml kernel: Console: switching to colour frame buffer device 128x48
Oct 03 14:08:08 grml kernel: fb0: VESA VGA frame buffer device
Oct 03 14:08:10 grml kernel: Console: switching to colour frame buffer device 160x50
Oct 03 14:08:10 grml kernel: vmwgfx 0000:00:02.0: [drm] fb0: vmwgfxdrmfb frame buffer device
```

Without any fb option is the same as `fb1024x768`. It changes from 128x48 to 160x50:
```
Oct 03 14:10:01 grml kernel: signal: max sigframe size: 1776
Oct 03 14:10:01 grml kernel: vesafb: framebuffer at 0xe0000000, mapped to 0x00000000147a3f66, using 3072k, total 34816k
Oct 03 14:10:01 grml kernel: Console: switching to colour frame buffer device 128x48
Oct 03 14:10:01 grml kernel: fb0: VESA VGA frame buffer device
Oct 03 14:10:03 grml kernel: Console: switching to colour frame buffer device 160x50
Oct 03 14:10:03 grml kernel: vmwgfx 0000:00:02.0: [drm] fb0: vmwgfxdrmfb frame buffer device
```

`fb1280x1024` changes from 160x64 to 160x64:
```
Oct 03 14:12:31 grml kernel: signal: max sigframe size: 1776
Oct 03 14:12:31 grml kernel: vesafb: framebuffer at 0xe0000000, mapped to 0x00000000444cae18, using 5120k, total 34816k
Oct 03 14:12:31 grml kernel: Console: switching to colour frame buffer device 160x64
Oct 03 14:12:31 grml kernel: fb0: VESA VGA frame buffer device
Oct 03 14:12:33 grml kernel: Console: switching to colour frame buffer device 160x64
Oct 03 14:12:33 grml kernel: vmwgfx 0000:00:02.0: [drm] fb0: vmwgfxdrmfb frame buffer device
```

`floppy` could not be tested, but considered as sunset feature, see: #211.

`hd` did not work for me.

`debug` does show a lot of log output.

`serial` could not be tested.

`dos` defaults to `Selection=3` (FreeDOS for 386 + FDXMS). This does not boot on my 64 Bit Virtualbox VM.
`Selection=4` (FreeDOS for 386+ HIMEM + EMM386) boot fine. We should consider changing the default selection.

**Comment by jkirk** [comment]
Some more findings:

When looking into https://github.com/grml/grml-live/blob/master/templates/boot/isolinux/hidden.cfg#L67-L70, there is a isolinux option `hda`. This options works and boots from disk, but is undocumented in [grml-cheatcodes.txt](https://github.com/grml/grml-live/blob/master/templates/GRML/grml-cheatcodes.txt).

Isolinux bootprompt options in [grml-cheatcodes.txt](https://github.com/grml/grml-live/blob/master/templates/GRML/grml-cheatcodes.txt#L4-L25) are not listed in the same order as the isolinux help splash [f3](https://github.com/grml/grml-live/blob/master/templates/boot/isolinux/f3). We should adjust the order.

**Comment by jkirk** [comment]
Drop `debian2hd` boot option, as it is broken under systemd and nobody seems to be using it, see: grml/grml-live#158.

**Comment by jkirk** [comment]
Just tested the framebuffer entries via QEMU (v7.2.13 with qemu-system-gui) and they seem to work. Updated the state of `fb1280x1024`, `fb1024x768` + `fb800x600` to working (✅).

FTR, Virtualbox does not seem to work with Framebuffer. Thx for the hint @zeha.

**Comment by jkirk** [comment]
Just tested DOS 6.22 Floppy Disk image from [here](https://www.allbootdisks.com/download/dos.html) via Virtualbox I82078 Floppy Controller. The floppy image did boot fine (via syslinux' `localboot 0x0` command).

hd tries to boot primary harddisk (via syslinux' `localboot 0x80` command). This does not work. hd1..3 call `localboot 0x81` to `localboot 0x83` respectability and do not work either).

`fd0` and `hd0` are undocumented. `fd0` (also) boots the floppy and `hd0` the primary harddisk (via syslinux' [chain.c32](https://wiki.syslinux.org/wiki/index.php?title=Comboot/chain.c32) COM32 module). We should update [grml-cheatcodes.txt](https://github.com/grml/grml-live/blob/master/templates/GRML/grml-cheatcodes.txt).

Updated https://github.com/grml/grml/issues/9#issuecomment-2391593095.

**Comment by jkirk** [comment]
`serial`: Tested serial console with QEMU (`qemu-system-x86_64 -m 2048 -cpu host -enable-kvm -serial stdio -cdrom ../build-daily/results/grml_isos/grml-small-pre2024.XX-rc0-amd64.iso`) which worked fine.

`dos`: Decided to remove FreeDos, added to the list in #211.

Updated https://github.com/grml/grml/issues/9#issuecomment-2391593095.

**Comment by jkirk** [comment]
`debug` is very verbose during the boot process.

The kernel is called with following parameters `append apm=power-off vga=791 verbose debug=vc initrd=/boot/%SHORT_NAME%/initrd.img boot=live live-media-path=/live/%GRML_NAME%/ bootid=%BOOTID% initcall_debug nomce net.ifnames=0`

The system ends up with:

```
root@grml ~ # cat /proc/cmdline
BOOT_IMAGE=/boot/grmlsmallamd64/vmlinuz initrd=/boot/grmlsmallamd64/initrd.img boot=live live-media-path=/live/grml-small-amd64/ bootid=grmlsmallamd64202412 apm=power-off vga=791 verbose debug=vc initcall nomce ne
t.ifnames=0 systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M
```

A Grml log file is also created (via grml-autoconfig), but it does show very much:
```
root@grml ~ # cat /tmp/grml.log.20241218 
systemd detected, no acpi(d) stuff needed.
```

**Comment by jkirk** [comment]
Isolinux bootprompt option `debug` and the "Boot option" `Debug Mode` have different kernel parameters:

[`templates/boot/isolinux/hidden.cfg`](https://github.com/grml/grml-live/blob/fd367801751aacfb056e801cf5d11d620b626d37/templates/boot/isolinux/hidden.cfg#L9)
`append apm=power-off vga=791 verbose debug=vc initrd=/boot/%SHORT_NAME%/initrd.img boot=live live-media-path=/live/%GRML_NAME%/ bootid=%BOOTID% initcall_debug nomce net.ifnames=0`

vs

[templates/boot/isolinux/grml.cfg](https://github.com/grml/grml-live/blob/fd367801751aacfb056e801cf5d11d620b626d37/templates/boot/isolinux/grml.cfg#L128):
`append initrd=/boot/%SHORT_NAME%/initrd.img boot=live live-media-path=/live/%GRML_NAME%/ bootid=%BOOTID% apm=power-off vga=791 verbose debug=vc initcall nomce net.ifnames=0 systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M`

So the later `grml.cfg` takes precedence.

We have three more duplicates:
```
❯ git grep -h "^label" templates/boot/isolinux/hidden.cfg templates/boot/isolinux/grml.cfg | sort | uniq -c | grep "^\s*2"
      2 label debug
      2 label nofb
      2 label nokms
      2 label serial
```
We should remove the according entries from `hidden.cfg`.

**Comment by jkirk** [comment]
Ad `video=ofonly`. Quoting: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1377878/comments/39
> Where this came from has been lost by the sands of time, but it doesn't 
relate to any PowerPC mac these days and hasn't been good advice since, 
well 10.04, and possibly before that.  Now that framebuffers are modules
 (that are blacklisted), the boot parameter video=ofonly in fact does 
nothing.  IT HAS TO BE CHANGED as it is just wasting people's time.
