### ISSUE TITLE
please include borgbackup for desaster recovery restore

### ISSUE THREAD

**Issue by flohoff** [grml/grml#99]
Hi,
please include the borgbackup package in the default build so one could issue a desaster recovery from within grml.

Thanks

Flo

**Comment by mika** [comment]
Thanks for reporting this! I just checked this with our current daily ISOs, installing the `borgbackup` package would pull in 4,575 kB of additional disk space. We already ship `restic`, though I'm afraid that our ISO size will only increase if pull in further and further backup solutions. :-/ IMO everything what's relevant for getting network access should be included, but additional tools can easily be installed on-the-fly if necessary (especially since a very specific version might be needed anyway in certain situations), so we shouldn't include it by default.

What do other folks think? @jkirk @formorer @evgeni @ft?

**Comment by evgeni** [comment]
I don't think that another 5MB would hurt, but I see the version requirement similar to @mika, so undecided overall.

**Comment by jkirk** [comment]
Not in grml-small, but I am fine to include it in grml-full.

**Comment by mika** [comment]
FTR, borgbackup will be included in grml-full and should be available as of tomorrow's daily ISOs as well as in the upcoming Grml stable release. Thanks everyone for your feedback.
